<?php
session_start();
if (!isset($_SESSION['admin_logged_in'])) { header("Location: login.php"); exit(); }
include 'db_config.php';

$this_month = date('Y-m');
$month_name = date('F Y');

// Fetch all sales for this month
$query = "SELECT * FROM sales WHERE sale_date LIKE '$this_month%' ORDER BY sale_date ASC";
$result = mysqli_query($conn, $query);

// Calculate Total
$total_query = mysqli_query($conn, "SELECT SUM(total_amount) as total FROM sales WHERE sale_date LIKE '$this_month%'");
$total_data = mysqli_fetch_assoc($total_query);
$grand_total = $total_data['total'] ?? 0;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Monthly Sales Report - <?php echo $month_name; ?></title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #333; line-height: 1.6; }
        .report-header { display: flex; justify-content: space-between; border-bottom: 3px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .logo-area img { height: 60px; margin-bottom: 10px; }
        .report-title { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f4f4f4; text-align: left; padding: 12px; border-bottom: 2px solid #ddd; font-size: 13px; }
        td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
        .total-section { margin-top: 30px; text-align: right; border-top: 2px solid #333; padding-top: 10px; }
        .btn-print { background: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; margin-bottom: 20px; }
        
        @media print {
            .btn-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>

    <button class="btn-print" onclick="window.print()">Download PDF / Print Report</button>

    <div class="report-header">
        <div class="logo-area">
            <img src="logo.png.jfif" alt="Logo">
            <h2 style="margin:0;">Receipt Pro</h2>
            <p style="margin:0; font-size:12px;">Digital Business Solutions</p>
        </div>
        <div class="report-title">
            <h1 style="margin:0; color:#007bff;">SALES REPORT</h1>
            <p style="margin:0;">Month: <strong><?php echo $month_name; ?></strong></p>
            <p style="margin:0; font-size:12px;">Generated on: <?php echo date('d M, Y'); ?></p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Customer Name</th>
                <th>Item Description</th>
                <th>Qty</th>
                <th>Total (₦)</th>
            </tr>
        </thead>
        <tbody>
            <?php if(mysqli_num_rows($result) > 0): ?>
                <?php while($row = mysqli_fetch_assoc($result)): ?>
                <tr>
                    <td><?php echo date('d M', strtotime($row['sale_date'])); ?></td>
                    <td><?php echo strtoupper($row['customer_name']); ?></td>
                    <td><?php echo $row['item_name']; ?></td>
                    <td><?php echo $row['quantity']; ?></td>
                    <td><?php echo number_format($row['total_amount'], 2); ?></td>
                </tr>
                <?php endwhile; ?>
            <?php else: ?>
                <tr><td colspan="5" style="text-align:center;">No sales recorded this month.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="total-section">
        <h3>Grand Total Revenue: ₦<?php echo number_format($grand_total, 2); ?></h3>
        <p style="font-size: 12px; color: #777;">Report verified and generated by Admin</p>
    </div>

</body>
</html>